name: lfric-atmos-training
channels:
- conda-forge

dependencies:
- python=3.12
- sphinx<9
- pydata-sphinx-theme
- sphinxcontrib-video
- sphinx-toolbox<4
- pip:
  # works for pip packages
  - git+https://github.com/bonartm/sphinxcontrib-quizdown.git

