name: lfric-atmos-training
channels:
- conda-forge
dependencies:
- python>=3.6
- sphinx
- sphinx_rtd_theme
- sphinxcontrib-video
- pip:
  # works for pip packages
  - git+https://github.com/bonartm/sphinxcontrib-quizdown.git
