name: Build Test

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Artifactory credentials
        uses: MetOffice/action-setup-artifactory@v1
        with:
          username: \"\"
          api-key: ${{ secrets.ARTIFACTORY_API_KEY }}

      - name: Sort out conda channels in ~/.condarc
        run: |
          conda config --remove channels defaults
          conda config --add channels conda-forge
          conda config --set channel_priority strict

      - name: Set up conda environment
        run: |
          conda update conda
          conda env create --name  lfric-atmos-training --file environment.yml

      - name: Build Documentation
        run: |
          eval "$(conda shell.bash hook)"
          conda activate  lfric-atmos-training
          make html
