# This workflow will build and deploy documentation to GitHub Pages
name: Deploy documentation to GitHub Pages

# Controls when the workflow will run
on:
  # Triggers the workflow when develop is updated
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v7

      - name: Install uv and Set up Python
        uses: astral-sh/setup-uv@v7
        with:
          python-version: "3.11"
          enable-cache: true

      - name: Install Graphviz
        run: sudo apt-get update && sudo apt-get install -y graphviz

      - name: Install dependencies from pyproject.toml
        run: |
          uv sync

      - name: Build documentation
        run: |
          uv run make clean html

      - name: Upload artifacts
        if: ${{ github.repository == 'MetOffice/LFRic-Atmosphere-Training' && github.ref_name == 'main' && github.event_name == 'push' }}
        uses: actions/upload-pages-artifact@v5
        with:
          name: github-pages
          path: build/html

      - name: Setup GitHub Pages
        if: ${{ github.repository == 'MetOffice/LFRic-Atmosphere-Training' && github.ref_name == 'main' && github.event_name == 'push' }}
        uses: actions/configure-pages@v6

      - name: Deploy to GitHub Pages
        id: deployment
        if: ${{ github.repository == 'MetOffice/LFRic-Atmosphere-Training' && github.ref_name == 'main' && github.event_name == 'push' }}
        uses: actions/deploy-pages@v5
