name: Test documentation

on:
  pull_request:
  push:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  documentation-building:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Install uv and Set up Python
        uses: astral-sh/setup-uv@v7
        with:
          python-version: "3.11"
          enable-cache: true

      - name: Install documentation system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --yes graphviz

      - name: Install dependencies from pyproject.toml
        run: |
          uv sync

      - name: Test documentation building
        run: |
          uv run make clean html linkcheck SPHINXOPTS='-Wn -D linkcheck_request_headers={"*":{"User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"}}'
